import {
  FileText, AlertTriangle, Stamp, UserX, FlaskConical, ArrowLeftRight
} from 'lucide-react'

export const services = [
  {
    slug: 'informasi-publik',
    title: 'Informasi Publik',
    description: 'Ajukan permohonan akses informasi publik sekolah sesuai UU KIP.',
    icon: FileText,
    estimasi: '1–7 Hari',
    color: 'from-blue-500 to-blue-600',
    lightBg: 'bg-blue-50',
    lightText: 'text-blue-700',
    borderColor: 'border-blue-200',
  },
  {
    slug: 'pengaduan',
    title: 'Pengaduan',
    description: 'Sampaikan pengaduan, saran, atau aspirasi terkait layanan sekolah.',
    icon: AlertTriangle,
    estimasi: '1–30 Hari',
    color: 'from-red-500 to-rose-600',
    lightBg: 'bg-red-50',
    lightText: 'text-red-700',
    borderColor: 'border-red-200',
  },
  {
    slug: 'legalisasi-ijazah',
    title: 'Legalisasi Ijazah',
    description: 'Pengajuan legalisasi ijazah lulusan SMPN 1 Wanayasa.',
    icon: Stamp,
    estimasi: '15–30 Menit',
    color: 'from-emerald-500 to-green-600',
    lightBg: 'bg-emerald-50',
    lightText: 'text-emerald-700',
    borderColor: 'border-emerald-200',
  },
  {
    slug: 'izin-siswa',
    title: 'Izin Siswa',
    description: 'Pengajuan surat izin ketidakhadiran siswa secara resmi.',
    icon: UserX,
    estimasi: '10–15 Menit',
    color: 'from-amber-500 to-orange-500',
    lightBg: 'bg-amber-50',
    lightText: 'text-amber-700',
    borderColor: 'border-amber-200',
  },
  {
    slug: 'penelitian',
    title: 'Penelitian / Observasi',
    description: 'Izin penelitian, PKL, atau observasi di lingkungan sekolah.',
    icon: FlaskConical,
    estimasi: '1 Hari',
    color: 'from-purple-500 to-violet-600',
    lightBg: 'bg-purple-50',
    lightText: 'text-purple-700',
    borderColor: 'border-purple-200',
  },
  {
    slug: 'mutasi-siswa',
    title: 'Mutasi Siswa',
    description: 'Proses mutasi siswa masuk maupun keluar dari SMPN 1 Wanayasa.',
    icon: ArrowLeftRight,
    estimasi: '1–7 Hari',
    color: 'from-cyan-500 to-teal-600',
    lightBg: 'bg-cyan-50',
    lightText: 'text-cyan-700',
    borderColor: 'border-cyan-200',
  },
]
